### ISSUE TITLE
Config file /etc/puppet/hiera.yaml not found

### ISSUE THREAD

**Issue by ssilvestro** [cloudbase/openstack-puppet-samples#2]
What am I doing wrong?

root@rack1-16:~# puppet apply --verbose openstack-aio-ubuntu-single-nic.pp
Info: Loading facts in /etc/puppet/modules/apt/lib/facter/apt_updates.rb
Info: Loading facts in /etc/puppet/modules/apt/lib/facter/apt_update_last_success.rb
Info: Loading facts in /etc/puppet/modules/mysql/lib/facter/mysql_server_id.rb
Info: Loading facts in /etc/puppet/modules/mysql/lib/facter/mysql_version.rb
Info: Loading facts in /etc/puppet/modules/concat/lib/facter/concat_basedir.rb
Info: Loading facts in /etc/puppet/modules/staging/lib/facter/staging_http_get.rb
Info: Loading facts in /etc/puppet/modules/staging/lib/facter/staging_windir.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/puppet_vardir.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/pe_version.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/root_home.rb
Info: Loading facts in /etc/puppet/modules/firewall/lib/facter/ip6tables_version.rb
Info: Loading facts in /etc/puppet/modules/firewall/lib/facter/iptables_persistent_version.rb
Info: Loading facts in /etc/puppet/modules/firewall/lib/facter/iptables_version.rb
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Error: Invalid db connection mysql://keystone:Passw0rd@/keystone at /etc/puppet/modules/keystone/manifests/init.pp:651 on node rack1-16.cloud.local
Error: Invalid db connection mysql://keystone:Passw0rd@/keystone at /etc/puppet/modules/keystone/manifests/init.pp:651 on node rack1-16.cloud.local
root@rack1-16:~#

**Comment by alexpilotti** [comment]
It's not getting an IP address. Definitely need to add a check for that and fail if missing.

The script looks for "eth0". You can set "$local_ip" manually.

**Comment by alexpilotti** [comment]
btw the title of the issue is misleading "Config file /etc/puppet/hiera.yaml not found" is just a warning from Puppet, which can be ignored as we don't rely on Hiera in this manifest

**Comment by ssilvestro** [comment]
Thank you for your help-- I think the problem was I had not created the admin bridge, but rather was assuming the script would create it for me. I started over from scratch, creating the bridge myself, and providing the name to the script. Things seem to be OK now! Thank you!
